# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c528b7e801ab3e82246f4d8ffd3cc5908d2d948b83d7c22d88e91e7d1f33346543f3c04255ac7cc18a98d4a6034909a4c54c846181ac40a7109821bddfb51de

test:
  secret_key_base: 18ad83ec616f87098b5d768fb9ab718f0cc9c3802293ccb2c9ea242ed56f00ea4be5768f95e97aa06902833e6bc8525ca05c7ff9a3608498d5d7857c8b4ea4e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
