source 'https://rubygems.org'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# Rails is a collection of libraries. All of the libraries are gems. Gems are housed in the gemfile.
gem 'rails', '4.2.3'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# shorter version of java script

# Use jquery as the JavaScript library
gem 'jquery-rails'
# very popular javascript library
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  #For all development test groups, we should have every single one of these gems every time b/c they make
  #debugging easier

  #to ensure the goodies that come from the gems are available in the stack is with command bundle,
  #you run it in the terminal. bundler is a gem that is responsible for integrating all gems included in gem file into stack

  gem 'byebug'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'pry'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'annotate'

# a gem file is not like a normal file, no class, no extra end at the end

end
